# The Basics
# --------------------
title:          "IPDB"
description:    "The Interplanetary Database."
url:            "https://ipdb.io"
email:          "contact@ipdb.io"

github:
    org:        "ipdb"
    repo:       "site"

analyticsID:    ""
typekitID:      "bko7hwo"

signup:
    button: Sign up for free (testnet)
    button_short: Sign up
    link: https://developers.ipdb.io/signup?plan_ids[]=2357355879577

login:
    button: Log in
    link: https://developers.ipdb.io/login

# Urls
# --------------------
permalink:      /:title/


# Generator
# --------------------
source:         ./_src
destination:    ./_dist


# Plugins
# --------------------
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from

exclude:
    - "*README.md"
